# Generated by Django 5.2.6 on 2025-10-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'منتج رقمي'), ('physical', 'منتج ملموس')], default='digital', max_length=10, verbose_name='نوع المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن المنتج (كجم)'),
        ),
    ]
